all:
  hosts:
    master:
      ansible_host: 192.168.56.3
      ip: 192.168.56.3
      access_ip: 192.168.56.3
    node1:
      ansible_host: 192.168.56.4
      ip: 192.168.56.4
      access_ip: 192.168.56.4
    node2:
      ansible_host: 192.168.56.5
      ip: 192.168.56.5
      access_ip: 192.168.56.5
    node3:
      ansible_host: 192.168.56.6
      ip: 192.168.56.6
      access_ip: 192.168.56.6
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
