---
- name: Configure DNS via NetworkManager
  hosts: all
  become: yes
  tasks:

    - name: Ensure NetworkManager is installed
      apt:
        name: network-manager
        state: present

    - name: Disable DNS management in NetworkManager
      lineinfile:
        path: /etc/NetworkManager/NetworkManager.conf
        regexp: '^dns='
        line: 'dns=none'
        create: yes

    - name: Apply DNS configuration for active connection
      command: nmcli connection show
      register: nmcli_output

    - name: Set DNS servers for active connection
      shell: |
        active_connection=$(nmcli -t -f NAME connection show --active | head -n 1)
        nmcli connection modify "$active_connection" ipv4.dns "192.168.0.190"
      when: nmcli_output is defined

    - name: Restart NetworkManager to apply changes
      systemd:
        name: NetworkManager
        state: restarted
