---
- name: Remove Docker
  hosts: all
  become: yes
  tasks:
    - name: Remove Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: absent
        purge: yes

    - name: Remove Docker GPG key
      file:
        path: /etc/apt/keyrings/docker.asc
        state: absent

    - name: Remove Docker repository
      file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Remove Docker data directory
      file:
        path: /var/lib/docker
        state: absent
