---
- name: Install Longhorn
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Add Longhorn Helm repository
      command: >
        helm repo add longhorn https://charts.longhorn.io
      register: add_repo
      ignore_errors: yes

    - name: Update Helm repositories
      command: helm repo update
      when: add_repo is not failed

    - name: Install Longhorn using Helm
      kubernetes.core.helm:
        name: longhorn
        chart_ref : longhorn/longhorn
        namespace: longhorn
        create_namespace: yes
        release_values :
          defaultSettings.replicaCount : 3
          defaultSettings.storageOverProvisioningPercentage : 200
          defaultSettings.storageMinimalAvailablePercentage : 10
      register: helm_install_result

    - name: Display Longhorn installation result
      debug:
        var: helm_install_result
