# permissions for end users to view playgrounds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: playground-operator
    app.kubernetes.io/managed-by: kustomize
  name: playground-viewer-role
rules:
- apiGroups:
  - playground.rfum.no
  resources:
  - playgrounds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - playground.rfum.no
  resources:
  - playgrounds/status
  verbs:
  - get
