# permissions for end users to edit playgrounds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: playground-operator
    app.kubernetes.io/managed-by: kustomize
  name: playground-editor-role
rules:
- apiGroups:
  - playground.rfum.no
  resources:
  - playgrounds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - playground.rfum.no
  resources:
  - playgrounds/status
  verbs:
  - get
