# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_BOX = 'k8sbase'
# # VM Port uncomment this to use NAT instead of DHCP
# VM_PORT = 8080
Vagrant.configure(2) do |config|
    config.vm.define "master" do |master|
      master.vm.box = VAGRANT_BOX
      master.vm.hostname = "master"
      # Set VM name in Virtualbox
      master.vm.provider "virtualbox" do |v|
        v.name = "master"
        v.memory = 2100
        v.gui = false
        v.check_guest_additions = false
      end
      master.vm.network "public_network"
      master.vm.network "private_network", ip: "192.168.56.3", virtualbox__intnet: true, name: "intnet"
    end


    config.vm.define "node1" do |node1|
      node1.vm.box = VAGRANT_BOX
      node1.vm.hostname = "node1"
      # Set VM name in Virtualbox
      node1.vm.provider "virtualbox" do |v|
        v.name = "node1"
        v.memory = 2500
        v.gui = false
        v.check_guest_additions = false
      end
      node1.vm.network "public_network"
      node1.vm.network "private_network", ip: "192.168.56.4", virtualbox__intnet: true, name: "intnet"
    end

    config.vm.define "node2" do |node2|
      node2.vm.box = VAGRANT_BOX
      node2.vm.hostname = "node2"
      # Set VM name in Virtualbox
      node2.vm.provider "virtualbox" do |v|
        v.name = "node2"
        v.memory = 2500
        v.gui = false
        v.check_guest_additions = false
      end
      node2.vm.network "public_network"
      node2.vm.network "private_network", ip: "192.168.56.5", virtualbox__intnet: true, name: "intnet"
    end


    config.vm.define "node3" do |node3|
      node3.vm.box = VAGRANT_BOX
      node3.vm.hostname = "node3"
      # Set VM name in Virtualbox
      node3.vm.provider "virtualbox" do |v|
        v.name = "node3"
        v.memory = 2500
        v.gui = false
        v.check_guest_additions = false
        end
      node3.vm.network "public_network"
      node3.vm.network "private_network", ip: "192.168.56.6", virtualbox__intnet: true, name: "intnet"
    end
  end

