---
- name: Remove Kubernetes Components
  hosts: all
  become: yes
  tasks:
    - name: Remove Kubernetes packages
      shell: |
          apt-get purge -y --allow-change-held-packages kubelet kubeadm kubectl

    - name: Remove Kubernetes GPG key
      file:
        path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        state: absent

    - name: Remove Kubernetes repository
      file:
        path: /etc/apt/sources.list.d/kubernetes.list
        state: absent

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Reboot the server
      reboot:
        reboot_timeout: 600
        test_command: whoami

    - name: Remove kubelet data directory
      file:
        path: /var/lib/kubelet
        state: absent

    - name: Remove kubeadm manifests directory
      file:
        path: /etc/kubernetes
        state: absent

    - name: Remove etcd directory
      file:
        path: /var/lib/etcd
        state: absent

